"""add indexing configuration to documents

Revision ID: d8ca228befb4
Revises: 9b0092e83eff
Create Date: 2026-07-31 21:14:52.432236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ca228befb4'
down_revision: Union[str, Sequence[str], None] = '9b0092e83eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('chunk_overlap', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'indexed_at')
    op.drop_column('documents', 'embedding_model')
    op.drop_column('documents', 'chunk_overlap')
    op.drop_column('documents', 'chunk_size')
    # ### end Alembic commands ###
